version: '3'
services:
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
  app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "3000:3000"
