version: '3'
services:
  redis:
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis-data:/data
  app:
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
    ports:
      - "3000:3000"
    environment:
       - PORT=3000
       - REDIS_HOST=redis
       - REDIS_PORT=6379
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
      - ./client/:/usr/src/app
    ports:
      - "8080:8080"
